### PR TITLE
Some initial fixes to get specs running under modern Rails versions

### PR DESCRIPTION
**Pull request by petergoldstein**
This is not complete, but makes some initial fixes to get specs running.

### CODE REVIEW

**Comment by petergoldstein** [comment]
@shadabahmed In case this is helpful.

**Comment by shadabahmed** [comment]
Thanks so much for this. I was working parallely on this. Hopefully this should help fix the rest of the issues

**Comment by petergoldstein** [comment]
@shadabahmed Still struggling with the duplicate entries under all Rails version.  Not sure why we're seeing 2x entries being written.

**Comment by shadabahmed** [comment]
Thanks for helping out. Merged your commits in this PR  #158 .

There are still two issues failing. It is caused when integration tests are run together with the unit tests. I will close this PR for now

**Comment by petergoldstein** [comment]
@shadabahmed Sounds good.  Thanks.

**Pull request closed without merging**
