### PR TITLE
Update travis config for latest ruby and rails versions

### PR DESCRIPTION
**Pull request by shadabahmed**
This bumps the rails and ruby versions on travis to include latest versions

### CODE REVIEW

**Comment by petergoldstein** [comment]
@shadabahmed Is this gem being actively maintained?  It looks like all supported versions of Rails fail the test suite.

**Comment by shadabahmed** [comment]
@petergoldstein - i am trying to fix all issues and support latest ruby/rails versions. Might take time since I haven't worked on this gem in a while

**Comment by petergoldstein** [comment]
@shadabahmed Ok, thanks.  Do you know what matrix of Rails versions you're planning to support in the near term (e.g. [6.1, 6.0, 5.2])?

**Comment by shadabahmed** [comment]
Immediate effort on 5.2 but will try latest rails and ruby3.0

**Pull request merged**
